### ISSUE TITLE
Dodanie linku do zaproszeń dla adminów

### ISSUE THREAD

**Issue by bambuchaAdm** [HackerspaceKRK/lobsters#7]
W panelu dla adminów byłoby miło gdyby pojawił się link do zaproszeń w lobstersy.

**Comment by Phitherek** [comment]
Ten issue jest niepoprawny, bo model jest taki:
1. Zaproszenia może przeglądać i wysyłać każdy
2. Użytkownicy którzy są moderatorami (nie adminami) mogą usuwać zaproszenia.

**Comment by Phitherek** [comment]
To be reviewed by @bambuchaAdm

**Comment by bambuchaAdm** [comment]
Fix in #15
